import type { Achievement, AchievementId } from '../types/quiz'

export const ACHIEVEMENTS: Achievement[] = [
  // ── Compte ──────────────────────────────────────────────────────────────────
  {
    id: 'premiers_pas',
    name: 'Premiers Pas',
    description: 'Créer son compte Pulse Quizz',
    icon: '🌱',
    progressTotal: null,
    tier: 'common',
  },

  // ── Volume — parties jouées ──────────────────────────────────────────────────
  {
    id: 'coup_d_envoi',
    name: "Coup d'Envoi",
    description: 'Jouer sa première partie',
    icon: '🎮',
    progressTotal: 1,
    tier: 'common',
  },
  {
    id: 'pris_au_jeu',
    name: 'Pris au Jeu',
    description: 'Jouer 10 parties',
    icon: '🎯',
    progressTotal: 10,
    tier: 'common',
  },
  {
    id: 'accro',
    name: 'Accro',
    description: 'Jouer 50 parties',
    icon: '🔁',
    progressTotal: 50,
    tier: 'rare',
  },
  {
    id: 'centenaire',
    name: 'Centenaire',
    description: 'Jouer 100 parties (tous modes)',
    icon: '🏆',
    progressTotal: 100,
    tier: 'epic',
  },
  {
    id: 'marathonien',
    name: 'Marathonien',
    description: 'Jouer 500 parties',
    icon: '🏃',
    progressTotal: 500,
    tier: 'epic',
  },

  // ── Compétitif ──────────────────────────────────────────────────────────────
  {
    id: 'premier_competiteur',
    name: 'Premier Compétiteur',
    description: 'Terminer sa première partie compétitive',
    icon: '⚡',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'combattant',
    name: 'Combattant',
    description: 'Jouer 50 parties compétitives',
    icon: '🥊',
    progressTotal: 50,
    tier: 'rare',
  },
  {
    id: 'gladiateur',
    name: 'Gladiateur',
    description: 'Jouer 100 parties compétitives',
    icon: '⚔️',
    progressTotal: 100,
    tier: 'epic',
  },
  {
    id: 'legende_de_lareme',
    name: "Légende de l'Arène",
    description: 'Jouer 1 000 parties compétitives',
    icon: '🏟️',
    progressTotal: 1000,
    tier: 'legendary',
  },

  // ── Séries ──────────────────────────────────────────────────────────────────
  {
    id: 'serie_de_feu',
    name: 'Série de Feu',
    description: "Enchaîner 10 bonnes réponses d'affilée en une partie",
    icon: '🔥',
    progressTotal: null,
    tier: 'rare',
  },
  {
    id: 'inferno',
    name: 'Inferno',
    description: "Enchaîner 20 bonnes réponses d'affilée",
    icon: '🌋',
    progressTotal: null,
    tier: 'epic',
  },
  {
    id: 'inarretable',
    name: 'Inarrêtable',
    description: "Enchaîner 30 bonnes réponses d'affilée",
    icon: '🌪️',
    progressTotal: null,
    tier: 'epic',
  },
  {
    id: 'transcendant',
    name: 'Transcendant',
    description: "Enchaîner 50 bonnes réponses d'affilée",
    icon: '✨',
    progressTotal: null,
    tier: 'legendary',
  },

  // ── Rapidité ────────────────────────────────────────────────────────────────
  {
    id: 'vif',
    name: 'Vif',
    description: 'Répondre correctement en moins de 5 secondes',
    icon: '🐇',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'foudroyant',
    name: 'Foudroyant',
    description: 'Répondre correctement en moins de 3 secondes',
    icon: '⚡',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'supersonique',
    name: 'Supersonique',
    description: 'Répondre correctement en moins de 2 secondes',
    icon: '🚀',
    progressTotal: null,
    tier: 'rare',
  },
  {
    id: 'instinct_pur',
    name: 'Instinct Pur',
    description: "Répondre correctement en moins d'1 seconde",
    icon: '🧠',
    progressTotal: null,
    tier: 'legendary',
  },

  // ── Perfection ──────────────────────────────────────────────────────────────
  {
    id: 'perfectionniste',
    name: 'Perfectionniste',
    description: 'Score parfait en mode normal (10/10)',
    icon: '💎',
    progressTotal: null,
    tier: 'rare',
  },

  // ── Points compétitif ───────────────────────────────────────────────────────
  {
    id: 'rookie',
    name: 'Rookie',
    description: 'Atteindre 1 000 points en compétitif',
    icon: '🌱',
    progressTotal: 1000,
    tier: 'common',
  },
  {
    id: 'challenger',
    name: 'Challenger',
    description: 'Atteindre 2 000 points en compétitif',
    icon: '🎖️',
    progressTotal: 2000,
    tier: 'common',
  },
  {
    id: 'performeur',
    name: 'Performeur',
    description: 'Atteindre 3 000 points en compétitif',
    icon: '📈',
    progressTotal: 3000,
    tier: 'common',
  },
  {
    id: 'chasseur_de_points',
    name: 'Chasseur de Points',
    description: 'Atteindre 5 000 points en compétitif',
    icon: '🎯',
    progressTotal: 5000,
    tier: 'rare',
  },
  {
    id: 'expert',
    name: 'Expert',
    description: 'Atteindre 10 000 points en compétitif',
    icon: '🔵',
    progressTotal: 10000,
    tier: 'rare',
  },
  {
    id: 'maitre',
    name: 'Maître',
    description: 'Atteindre 20 000 points en compétitif',
    icon: '🟣',
    progressTotal: 20000,
    tier: 'epic',
  },
  {
    id: 'grand_maitre',
    name: 'Grand Maître',
    description: 'Atteindre 30 000 points en compétitif',
    icon: '💜',
    progressTotal: 30000,
    tier: 'epic',
  },
  {
    id: 'legende',
    name: 'Légende',
    description: 'Atteindre 50 000 points en compétitif',
    icon: '🌟',
    progressTotal: 50000,
    tier: 'legendary',
  },
  {
    id: 'mythique',
    name: 'Mythique',
    description: 'Atteindre 100 000 points en compétitif',
    icon: '💫',
    progressTotal: 100000,
    tier: 'legendary',
  },

  // ── Exploration ─────────────────────────────────────────────────────────────
  {
    id: 'touche_a_tout',
    name: 'Touche-à-Tout',
    description: 'Jouer dans les 7 catégories disponibles',
    icon: '🗺️',
    progressTotal: 7,
    tier: 'common',
  },
  {
    id: 'polyvalent',
    name: 'Polyvalent',
    description: 'Jouer en mode Normal et en mode Compétitif',
    icon: '🔄',
    progressTotal: null,
    tier: 'common',
  },

  // ── Classement ──────────────────────────────────────────────────────────────
  {
    id: 'dans_l_elite',
    name: "Dans l'Élite",
    description: 'Entrer dans le top 100 du classement compétitif',
    icon: '🏅',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'reconnu',
    name: 'Reconnu',
    description: 'Entrer dans le top 50 du classement compétitif',
    icon: '🎗️',
    progressTotal: null,
    tier: 'rare',
  },
  {
    id: 'les_25',
    name: 'Les 25',
    description: 'Entrer dans le top 25 du classement compétitif',
    icon: '💪',
    progressTotal: null,
    tier: 'rare',
  },
  {
    id: 'les_meilleurs',
    name: 'Les Meilleurs',
    description: 'Entrer dans le top 10 du classement compétitif',
    icon: '🔟',
    progressTotal: null,
    tier: 'epic',
  },
  {
    id: 'sur_le_podium',
    name: 'Sur le Podium',
    description: 'Entrer dans le top 3 du classement compétitif',
    icon: '🥈',
    progressTotal: null,
    tier: 'legendary',
  },
  {
    id: 'sans_rival',
    name: 'Sans Rival',
    description: 'Être numéro 1 du classement compétitif',
    icon: '👑',
    progressTotal: null,
    tier: 'legendary',
  },

  // ── Personnalisation ────────────────────────────────────────────────────────
  {
    id: 'premier_pin',
    name: 'Premier Pin',
    description: 'Épingler un badge dans le leaderboard',
    icon: '📌',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'collectionneur',
    name: 'Collectionneur',
    description: 'Épingler 3 badges dans le leaderboard',
    icon: '🗂️',
    progressTotal: null,
    tier: 'rare',
  },
  {
    id: 'reinvention',
    name: 'Réinvention',
    description: 'Changer son pseudo',
    icon: '✏️',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'nouveau_visage',
    name: 'Nouveau Visage',
    description: 'Changer son avatar',
    icon: '🎭',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'mon_histoire',
    name: 'Mon Histoire',
    description: 'Renseigner sa description de profil',
    icon: '📖',
    progressTotal: null,
    tier: 'common',
  },

  // ── Défi Journalier — séries ─────────────────────────────────────────────────
  {
    id: 'daily_premier_defi',
    name: 'Premier Défi',
    description: 'Participer au défi journalier pour la première fois',
    icon: '📅',
    progressTotal: 1,
    tier: 'common',
  },
  {
    id: 'daily_serie_3',
    name: 'Série de 3',
    description: 'Jouer 3 défis journaliers consécutifs',
    icon: '🔥',
    progressTotal: 3,
    tier: 'rare',
  },
  {
    id: 'daily_semaine_de_feu',
    name: 'Semaine de Feu',
    description: 'Jouer 7 défis journaliers consécutifs',
    icon: '⚡',
    progressTotal: 7,
    tier: 'epic',
  },
  {
    id: 'daily_quinzaine',
    name: 'Quinzaine',
    description: 'Jouer 14 défis journaliers consécutifs',
    icon: '🌩️',
    progressTotal: 14,
    tier: 'epic',
  },
  {
    id: 'daily_mois_de_fer',
    name: 'Mois de Fer',
    description: 'Jouer 30 défis journaliers consécutifs',
    icon: '🌟',
    progressTotal: 30,
    tier: 'legendary',
  },
  {
    id: 'daily_centenaire',
    name: 'Centenaire Journalier',
    description: 'Jouer 100 défis journaliers consécutifs',
    icon: '💎',
    progressTotal: 100,
    tier: 'legendary',
  },

  // ── Défi Journalier — scores ─────────────────────────────────────────────────
  {
    id: 'daily_score_parfait',
    name: 'Score Parfait',
    description: 'Réussir un 10/10 au défi journalier',
    icon: '✨',
    progressTotal: null,
    tier: 'common',
  },
  {
    id: 'daily_sniper',
    name: 'Sniper',
    description: 'Réussir 5 scores parfaits au défi journalier',
    icon: '🎯',
    progressTotal: 5,
    tier: 'rare',
  },
  {
    id: 'daily_infaillible',
    name: 'Infaillible',
    description: 'Score parfait 10/10 avec le multiplicateur ×3 actif',
    icon: '🔥',
    progressTotal: null,
    tier: 'epic',
  },
  {
    id: 'daily_podium',
    name: 'Podium Journalier',
    description: 'Terminer dans le top 3 du classement du jour',
    icon: '🏆',
    progressTotal: null,
    tier: 'legendary',
  },
  {
    id: 'daily_roi_du_jour',
    name: 'Roi du Jour',
    description: 'Terminer #1 du classement du jour',
    icon: '👑',
    progressTotal: null,
    tier: 'legendary',
  },
]

export const ACHIEVEMENT_MAP: Record<AchievementId, Achievement> =
  Object.fromEntries(ACHIEVEMENTS.map(a => [a.id, a])) as Record<AchievementId, Achievement>
