// Mock data shared across all daily recap previews.
// Matches the structure coming from DailyTheme + DailyEntry + QuestionResult + DailyStreak.

window.MOCK = {
  theme: {
    date: '2026-04-16',
    dateLabel: 'mercredi 16 avril 2026',
    emoji: '🎸',
    title: 'Rétro 80s',
    description: 'Dix questions pour tester ton œil et ton oreille sur la décennie la plus stylée.',
  },
  entry: {
    score: 1847,
    correct: 8,
    total: 10,
    xpEarned: 285,
    pulsesEarned: 78,
    multiplier: 1.5,
  },
  leaderboard: {
    rank: 12,
    totalPlayers: 1247,
    rankDelta: null, // pour le contexte daily, on montre le rang final figé
  },
  streak: {
    current: 5,
    next: { needed: 2, label: '×2.0 dans' },
  },
  achievements: [
    {
      id: 'daily_top_100',
      name: 'Top 100 du jour',
      description: 'Termine dans le top 100 d\'un défi quotidien.',
      icon: '🎯',
      tier: 'epic',
      glow: '#8B5CF6',
    },
    {
      id: 'streak_5',
      name: 'Cinq d\'affilée',
      description: 'Joue au défi quotidien 5 jours de suite.',
      icon: '🔥',
      tier: 'rare',
      glow: '#3B82F6',
    },
  ],
  questions: [
    {
      n: 1,
      question: 'Quel film de 1985 met en scène Marty McFly au volant d\'une DeLorean ?',
      userAnswer: 'Retour vers le futur',
      correctAnswer: 'Retour vers le futur',
      isCorrect: true,
      timeSpent: 3.2,
      points: 300,
      multiplier: 3,
      anecdote: 'Michael J. Fox tournait Family Ties le jour et Retour vers le futur la nuit — il dormait 4h par nuit pendant six mois.',
    },
    {
      n: 2,
      question: 'Qui a chanté "Like a Virgin" en 1984 ?',
      userAnswer: 'Madonna',
      correctAnswer: 'Madonna',
      isCorrect: true,
      timeSpent: 1.8,
      points: 300,
      multiplier: 3,
      anecdote: 'La bague "Boy Toy" que Madonna portait aux MTV Awards 84 avait été achetée 9 $ dans un marché aux puces de New York.',
    },
    {
      n: 3,
      question: 'Quelle console Nintendo sort en Amérique du Nord en 1985 ?',
      userAnswer: 'NES',
      correctAnswer: 'NES',
      isCorrect: true,
      timeSpent: 4.9,
      points: 200,
      multiplier: 2,
      anecdote: 'Nintendo l\'a déguisée en jouet robot (le R.O.B.) pour convaincre les vendeurs américains traumatisés par le krach du jeu vidéo de 1983.',
    },
    {
      n: 4,
      question: 'En quelle année tombe le Mur de Berlin ?',
      userAnswer: '1989',
      correctAnswer: '1989',
      isCorrect: true,
      timeSpent: 2.1,
      points: 300,
      multiplier: 3,
      anecdote: 'La chute a été déclenchée par une conférence de presse confuse — un porte-parole a dit "tout de suite" au lieu de "bientôt" concernant la libre circulation.',
    },
    {
      n: 5,
      question: 'Quel groupe chante "Bohemian Rhapsody" en live lors du Live Aid 1985 ?',
      userAnswer: 'The Who',
      correctAnswer: 'Queen',
      isCorrect: false,
      timeSpent: 6.4,
      points: 0,
      multiplier: 0,
      anecdote: 'La performance de Queen de 21 minutes est considérée par beaucoup comme le meilleur set rock jamais joué — Freddie a chauffé 72 000 personnes en 90 secondes.',
    },
    {
      n: 6,
      question: 'Quel film de James Cameron sort en 1984 avec Arnold Schwarzenegger ?',
      userAnswer: 'Terminator',
      correctAnswer: 'Terminator',
      isCorrect: true,
      timeSpent: 2.9,
      points: 300,
      multiplier: 3,
      anecdote: 'Cameron a vendu le scénario pour 1 $ à Gale Anne Hurd à une seule condition : qu\'elle le laisse réaliser. Le film a rapporté 78 M$.',
    },
    {
      n: 7,
      question: 'Quel jeu d\'arcade japonais fait fureur en 1980 ?',
      userAnswer: 'Pac-Man',
      correctAnswer: 'Pac-Man',
      isCorrect: true,
      timeSpent: 1.4,
      points: 300,
      multiplier: 3,
      anecdote: 'Le design de Pac-Man a été inspiré à Toru Iwatani par une pizza à laquelle il manquait une part.',
    },
    {
      n: 8,
      question: 'Quelle série se passe à Hill Valley ?',
      userAnswer: null,
      correctAnswer: 'Retour vers le futur',
      isCorrect: false,
      timeSpent: 10,
      points: 0,
      multiplier: 0,
      anecdote: 'Hill Valley apparaît dans les trois films de la trilogie — les décorateurs ont recyclé la même place centrale à trois époques différentes sur le même backlot d\'Universal.',
    },
    {
      n: 9,
      question: 'Quel ordinateur familial lancé en 1982 dépassera 12 millions d\'unités vendues ?',
      userAnswer: 'Commodore 64',
      correctAnswer: 'Commodore 64',
      isCorrect: true,
      timeSpent: 3.8,
      points: 300,
      multiplier: 3,
      anecdote: 'Le C64 détient toujours le record Guinness de l\'ordinateur personnel le plus vendu de tous les temps, tous modèles confondus.',
    },
    {
      n: 10,
      question: 'Qui peint "Radiant Baby" sur les murs du métro new-yorkais au début des années 80 ?',
      userAnswer: 'Keith Haring',
      correctAnswer: 'Keith Haring',
      isCorrect: true,
      timeSpent: 2.5,
      points: 300,
      multiplier: 3,
      anecdote: 'Haring se faisait arrêter régulièrement — il considérait les panneaux publicitaires noirs vides du métro comme sa "galerie gratuite" pour toucher le peuple.',
    },
  ],
}
